      - name: Check iOS files
        run: |
          find ios -maxdepth 3 -type f | sort

      - name: Build iOS
        run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
